openapi: "3.0.1"
info:
  title: "POST-API"
  version: "2026-02-20"
paths:
  /metrics:
    options:
      x-amazon-apigateway-integration:
        type: "mock"
        requestTemplates:
          application/json: '{"statusCode": 200}'
        responses:
          default:
            statusCode: "200"
    post:
      responses:
        default:
          description: "Default response for POST /metrics"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "${lambda_arn}"
        connectionType: "INTERNET"
  /state:
    options:
      x-amazon-apigateway-integration:
        type: "mock"
        requestTemplates:
          application/json: '{"statusCode": 200}'
        responses:
          default:
            statusCode: "200"
    get:
      parameters:
      - name: userId
        in: query
        required: true
        schema:
          type: string
      - name: sessionId
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "User state retrieved"
        "404":
          description: "State not found"
        "500":
          description: "Server error"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "${user_state_lambda_arn}"
        connectionType: "INTERNET"
x-amazon-apigateway-cors:
  allowMethods:
  - "OPTIONS"
  - "POST"
  - "GET"
  allowHeaders:
  - "authorization"
  - "content-type"
  - "x-api-key"
  maxAge: 0
  allowCredentials: false
  allowOrigins:
  - "*"
x-amazon-apigateway-importexport-version: "1.0"
